apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: crypto-processing
spec:
  selector:
    app: cassandra
  ports:
    - name: intra-node
      port: 7006
      targetPort: 7006
    - name: cql
      port: 9042
      targetPort: 9042
  type: ClusterIP