apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: crypto-processing
spec:
  selector:
    app: spark-master
  ports:
    - name: master
      port: 7077
      targetPort: 7077
    - name: webui
      port: 8080
      targetPort: 8080
  type: ClusterIP