apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-1
  namespace: crypto-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker-1
  template:
    metadata:
      labels:
        app: spark-worker-1
    spec:
      containers:
        - name: spark-worker
          image: bitnami/spark:3.5
          env:
            - name: SPARK_MODE
              value: "worker"
            - name: SPARK_MASTER_URL
              value: "spark://spark-master:7077"
            - name: SPARK_WORKER_MEMORY
              value: "1g"
            - name: SPARK_WORKER_CORES
              value: "1"
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: "no"
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_SSL_ENABLED
              value: "no"
            - name: SPARK_WORKER_OPTS
              value: "-Dspark.worker.cleanup.enabled=true -Dspark.worker.cleanup.interval=3600"
          volumeMounts:
            - name: spark-worker-logs
              mountPath: /opt/bitnami/spark/logs
            - name: spark-worker-work
              mountPath: /opt/bitnami/spark/work
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - ps aux | grep "[o]rg.apache.spark.deploy.worker.Worker" || exit 1
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: spark-worker-logs
          emptyDir: {}
        - name: spark-worker-work
          emptyDir: {}